# permissions for end users to edit serviceaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceaccount-editor-role
rules:
- apiGroups:
  - auth.itsumma.ru
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.itsumma.ru
  resources:
  - serviceaccounts/status
  verbs:
  - get
- apiGroups:
    - ""
  resources:
    - serviceaccounts
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch:q:q
