# permissions for end users to view serviceaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceaccount-viewer-role
rules:
- apiGroups:
  - auth.itsumma.ru
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - auth.itsumma.ru
  resources:
  - serviceaccounts/status
  verbs:
  - get
